# Отрицательное биномиальное распределение

3.1 Нахождение выборочного среднего и выборочной дисперсии

In [3]:
import numpy as np

def Geom(prob):
    j=0
    k = np.random.binomial(size=1, n=1, p=prob)
    while k==0:
        j=j+1
        k = np.random.binomial(size=1, n=1, p=prob)
    return j

def Neg_Binom(r, prob): #r, prob - параметры, задающие NB распределение
    xi = 0
    for i in range(r):
        xi += Geom(prob)
    return xi

def NewSample(sample, p, r):
    lstRes = np.array([])
    i = 1
    for i in range(sample):
        lstRes = np.append(lstRes, Neg_Binom(r, p))
    return lstRes

a1 = np.arange(100000) #5 реализаций выборок при n = 100000
a = np.array([])
i = 1
for i in range(5):
    a = np.append(a, a1)
a = a.reshape([5, 100000])

a[0] = NewSample(100000, 0.6, 3)
a[1] = NewSample(100000, 0.6, 3)
a[2] = NewSample(100000, 0.6, 3)
a[3] = NewSample(100000, 0.6, 3)
a[4] = NewSample(100000, 0.6, 3)

b1 = np.arange(1000) #5 реализаций выборок при n = 1000
b = np.array([])
i = 1
for i in range(5):
    b = np.append(b, b1)
b = b.reshape([5, 1000])

b[0] = NewSample(1000, 0.6, 3)
b[1] = NewSample(1000, 0.6, 3)
b[2] = NewSample(1000, 0.6, 3)
b[3] = NewSample(1000, 0.6, 3)
b[4] = NewSample(1000, 0.6, 3)

c1 = np.arange(100) #при n = 100
c = np.array([])
i = 1
for i in range(5):
    c = np.append(c, c1)
c = c.reshape([5, 100])

c[0] = NewSample(100, 0.6, 3)
c[1] = NewSample(100, 0.6, 3)
c[2] = NewSample(100, 0.6, 3)
c[3] = NewSample(100, 0.6, 3)
c[4] = NewSample(100, 0.6, 3)

d1 = np.arange(10) # n = 10
d = np.array([])
i = 1
for i in range(5):
    d = np.append(d, d1)
d = d.reshape([5, 10])

d[0] = NewSample(10, 0.6, 3)
d[1] = NewSample(10, 0.6, 3)
d[2] = NewSample(10, 0.6, 3)
d[3] = NewSample(10, 0.6, 3)
d[4] = NewSample(10, 0.6, 3)

e1 = np.arange(5) # n = 5
e = np.array([])
i = 1
for i in range(5):
    e = np.append(e, e1)
e = e.reshape([5, 5])

e[0] = NewSample(5, 0.6, 3)
e[1] = NewSample(5, 0.6, 3)
e[2] = NewSample(5, 0.6, 3)
e[3] = NewSample(5, 0.6, 3)
e[4] = NewSample(5, 0.6, 3)

In [4]:
VibAverA = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочное среднее для выборок с n = 100000
for i in range(5): VibAverA[i] = np.sum(a[i])/len(a[i])
print(VibAverA)

[1.99973 2.00247 1.99974 2.00725 2.00056]


In [8]:
VibAverB = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочное среднее для выборок с n = 1000
for i in range(5):
    VibAverB[i] = np.sum(b[i])/len(b[i])
print(VibAverB)

[2.031 1.998 2.091 1.972 1.889]


In [9]:
VibAverC = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочное среднее для выборок с n = 100
for i in range(5):
    VibAverC[i] = np.sum(c[i])/len(c[i])
print(VibAverC)

[1.73 2.18 1.78 1.99 1.85]


In [10]:
VibAverD = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочное среднее для выборок с n = 10
for i in range(5): 
    VibAverD[i] = np.sum(d[i])/len(d[i])
print(VibAverD)

[2.1 1.3 1.1 1.5 2.1]


In [11]:
VibAverE = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочное среднее для выборок с n = 5
for i in range(5):
    VibAverE[i] = np.sum(e[i])/len(e[i])
print(VibAverE)

[3.2 2.4 2.6 2.  3.8]


In [12]:
VibDispA = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочную дисперсию для выборок с n = 100000
for i in range(5):
    for t in a[i]: VibDispA[i] = VibDispA[i] + ((t - VibAverA[i])**2)/len(a[i])
print(VibDispA)

[3.35176993 3.3517239  3.32831993 3.36127744 3.33073969]


In [13]:
VibDispB = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочную дисперсию для выборок с n = 1000
for i in range(5):
    for t in b[i]: VibDispB[i] = VibDispB[i] + ((t - VibAverB[i])**2)/len(b[i])
print(VibDispB)

[3.498039 3.089996 3.604719 3.029216 3.142679]


In [14]:
VibDispC = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочную дисперсию для выборок с n = 100
for i in range(5):
    for t in c[i]: VibDispC[i] = VibDispC[i] + ((t - VibAverC[i])**2)/len(c[i])
print(VibDispC)

[3.6371 4.8076 2.3316 3.6099 3.0475]


In [15]:
VibDispD = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочную дисперсию для выборок с n = 10
for i in range(5):
    for t in d[i]: VibDispD[i] = VibDispD[i] + ((t - VibAverD[i])**2)/len(d[i])
print(VibDispD)

[2.69 2.01 1.29 0.65 4.69]


In [16]:
VibDispE = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) # Ищем выборочную дисперсию для выборок с n = 5
for i in range(5):
    for t in e[i]: VibDispE[i] = VibDispE[i] + ((t - VibAverE[i])**2)/len(e[i])
print(VibDispE)

[ 1.76  1.04  4.64  1.6  12.56]


In [32]:
#Сравнение получившихся значений выборочного среднего для разных выборок и значений оцениваемого параметра - мат.ожидания
import math

def MatComp(sample, p, r):
    for t in sample:
        print(str(math.sqrt((t - float(r*(1-p)/p))**2)),)
    print()
    
MatComp(VibAverE, 0.6, 3) # сравнение с выборками при n = 5

1.1999999999999997
0.39999999999999947
0.5999999999999996
4.440892098500626e-16
1.7999999999999994



In [33]:
MatComp(VibAverD, 0.6, 3) # сравнение с выборками при n = 10

0.09999999999999964
0.7000000000000004
0.9000000000000004
0.5000000000000004
0.09999999999999964



In [34]:
MatComp(VibAverC, 0.6, 3) # сравнение с выборками при n = 100

0.27000000000000046
0.17999999999999972
0.22000000000000042
0.010000000000000453
0.15000000000000036



In [35]:
MatComp(VibAverB, 0.6, 3) # сравнение с выборками при n = 1000

0.030999999999999694
0.002000000000000446
0.09099999999999975
0.02800000000000047
0.11100000000000043



In [36]:
MatComp(VibAverA, 0.6, 3) # сравнение с выборками при n = 100000

0.00027000000000043656
0.00246999999999975
0.00026000000000037105
0.007249999999999535
0.0005599999999996719



In [37]:
#Сравнение получившихся значений выборочной дисперсии для разных выборок и значений оцениваемого параметра - дисперсии
def DispComp(sample, p, r):
    for t in sample:
        print(str(math.sqrt((t - float(r*(1-p)/(p**2)))**2)),)
    print()
    
DispComp(VibDispE, 0.6, 3) # сравнение с выборками при n = 5

1.573333333333334
2.293333333333334
1.3066666666666666
1.7333333333333338
9.226666666666667



In [38]:
DispComp(VibDispD, 0.6, 3) # сравнение с выборками при n = 10

0.643333333333334
1.3233333333333337
2.043333333333334
2.6833333333333336
1.3566666666666682



In [39]:
DispComp(VibDispC, 0.6, 3) # сравнение с выборками при n = 100

0.30376666666667074
1.4742666666666704
1.0017333333333358
0.2765666666666702
0.28583333333333316



In [40]:
DispComp(VibDispB, 0.6, 3) # сравнение с выборками при n = 1000

0.16470566666669129
0.2433373333333133
0.2713856666666712
0.3041173333333158
0.19065433333332704



In [41]:
DispComp(VibDispA, 0.6, 3) # сравнение с выборками при n = 100000

0.018436593765510434
0.01839056576610565
0.005013400933726597
0.02794410416573756
0.002593646932107063



In [43]:
print('Мат. ожидание равно '+str(math.sqrt((t - float(3*(1-0.6)/0.6))**2)))
print('Дисперсия равна '+str(math.sqrt((t - float(3*(1-0.6)/(0.6**2)))**2)))

Мат. ожидание равно 2.9999999999999996
Дисперсия равна 1.666666666666666
